# PHP CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-php/ for more details

version: 2

defaults: &defaults
  context: org-global

workflows:
  version: 2
  # When pushed to "master", deploy to "prod".
  deploy:
    jobs:
      - deploy:
          <<: *defaults
          filters:
            branches:
              only: master

jobs:
  deploy:
    docker:
      - image: previousnext/pnx-packager
    working_directory: /data
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Build and Deploy
          command: |
            VERSION=$(git describe --tags --always)
            SKPR_ENV=prod
            echo "Building version: ${VERSION}"
            docker login -u $DOCKER_USER -p $DOCKER_PASS
            docker build -t previousnext/commit-weather:${VERSION} $(pwd)
            docker push previousnext/commit-weather:${VERSION}
            skpr deploy ${SKPR_ENV} ${VERSION}
            notify --channel="#sys-ops-builds" --username="Skipper" --icon-emoji=":k8s:" --message="Deployed \`${VERSION}\` from \`${CIRCLE_BRANCH}\` to *${SKPR_ENV}*"
