# PHP CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-php/ for more details
#
# Environment variables:
# Most environment variables are set at the org level. You need to explicitly
# set the following per project:
#   - SLACK_WEBHOOK_URL

version: 2

defaults: &defaults
  context: org-global

workflows:
  version: 2
  # When pushed to "master", deploy to "dev".
  # When pushed to "releases", deploy to "staging".
  # Promote deploy from "staging" to "production".
  deploy:
    jobs:
      - build:
          <<: *defaults
          filters:
            branches:
              only: master
      - approve:
          type: approval
          requires:
            - build
      - deploy_prod:
          <<: *defaults
          requires:
            - approve

jobs:
  build:
    docker:
      - image: previousnext/pnx-packager
    working_directory: /data
    steps:
      - checkout
      - setup_remote_docker
      - restore_cache:
          keys:
            - deps-{{ arch }}-{{ checksum "package-lock.lock" }}
      - run:
          name: Build and Deploy
          command: |
            VERSION=$(git describe --tags --always)
            echo "Building version: ${VERSION}"
            docker login -u $DOCKER_USER -p $DOCKER_PASS
            docker build -t previousnext/commit-weather:${VERSION} $(pwd)
            docker push previousnext/commit-weather:${VERSION}
            notify --channel="#backend" --username="Skipper" --icon-emoji=":k8s:" --message="Deployed \`${VERSION}\` from \`${CIRCLE_BRANCH}\` to *${SKPR_ENV}*"
            if [[ -v NOTIFY_UPCOMING_APPROVAL ]] ; then notify --channel="#backend" --username="Skipper" --icon-emoji=":k8s:" --message="Approve deployment of \`${VERSION}\` to *${NOTIFY_UPCOMING_APPROVAL}*: https://circleci.com/workflow-run/${CIRCLE_WORKFLOW_ID}" ; fi
          #skpr deploy ${SKPR_ENV} ${VERSION}

  deploy_prod:
    docker:
      - image: previousnext/pnx-packager
    working_directory: /data
    steps:
      - checkout
      - run:
          name: Build and Deploy
          command: |
            VERSION=$(git describe --tags --always)
            skpr deploy ${SKPR_ENV} ${VERSION}
            notify --channel="#backend" --username="Skipper" --icon-emoji=":k8s:" --message="Deployed \`${VERSION}\` from \`${CIRCLE_BRANCH}\` to *${SKPR_ENV}*"
          #SKPR_ENV=prod
